name: Main
on:
  push: {}
  pull_request: {}
env:
  FORCE_COLOR: 2
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: bahmutov/npm-install@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: demo
      - run: npm run test

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run build

  # Create the new Github Release
  Release:
    runs-on: ubuntu-latest
    needs: ["Test", "Build"]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Prepare changelog
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          sed "1,/## ${{ env.RELEASE_VERSION }}/d;/##/Q;/^[[:space:]]*$/d" CHANGELOG.md > ${{ github.workflow }}-release-CHANGELOG.txt
      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workflow }}-release-CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
